version: "3"
services:
  app:
    command: [
      "auto-mcs-ttyd",
      "-W",
      "-t", "disableLeaveAlert=true",
      "-t", "titleFixed=auto-mcs (docker)",
      "-t", "fontSize=20",
      "-t", 'theme={"background": "#1A1A1A"}',
      "-p", "8080",
      "-c", "root:auto-mcs",
      "tmux", "-u", "-2", "new", "-A", "-s", "-c",
      "./auto-mcs"
    ]

    image: auto-mcs
    container_name: auto-mcs
    build: .
    stdin_open: true
    tty: true
    ports:

      # ttyd web UI
      - "8080:8080"

      # Telepath API (auto-mcs)
      - "7001:7001"

      # Add more ports based on the servers you create
      - "25565:25565"

    volumes:
      - auto-mcs-data:/root/.auto-mcs

volumes:
  auto-mcs-data:
